export class BuilderNameConstants{
  static readonly MINE_LOGIN:string='mine_login'
  static readonly MINE_LOGINCODE:string='mine_loginCode'
  static readonly MINE_MINEPAGE:string='mine_minePage'
  static readonly HOME:string='home_home'
  static readonly ROOM_LIST:string='home_roomlist'
  static readonly ROOM_PAGE:string='home_roompage'
}

export class RouterNameConstants{
  static readonly ENTRY_HAP:string='EntryHap_Router'
}